### ISSUE TITLE
--deps should also look for jq

### ISSUE THREAD

**Issue by MikeWallaceDev** [dshoreman/nextshot#61]
I tried to take a screenshot but got "jq not found". Installing it fixes the error but it doesnt show in --deps

![image](https://user-images.githubusercontent.com/1521802/59570320-4c37ec80-908e-11e9-96a6-27fbae964f01.png)

**Comment by dshoreman** [comment]
@MikeWallaceDev Thanks for finding this! Fixed in v1.2.3.
