### ISSUE TITLE
Nextshot doesn't work corretly if locale isn't set to US

### ISSUE THREAD

**Issue by e-alfred** [dshoreman/nextshot#64]
Hello, 

I can't take a screenshot of an area or window if the numeric location isn't set to en_US.UTF-8 because BC doesn't seem to be able to do the calculation in a correct way:
```

$ nextshot -t
/usr/bin/nextshot: Line 343: printf: 1.00000000000000000000: Invalid Number.
/usr/bin/nextshot: Line 343: printf: .39215686274509803921: Invalid Number.
/usr/bin/nextshot: Line 343: printf: .70588235294117647058: Invalid Number.
Starting Nextshot tray menu...
```

If I start Nextshot using `LC_NUMERIC="en_US.UTF-8" /usr/bin/nextshot -t` everything works perfectly fine.

**Comment by dshoreman** [comment]
@e-alfred If you open a fresh terminal without setting `LC_NUMERIC`, what's the output of `locale`?

**Comment by e-alfred** [comment]
Currently it is this:

`LC_NUMERIC="de_AT.UTF-8"`

**Comment by dshoreman** [comment]
Thanks, when I'm back in linux I'll do some testing with your locale and
see if I can replicate. My guess is the European decimal separator being a
comma instead of a dot is confusing things somewhere.

Hopefully it'll be as simple as converting to/from the local decimal
format... Watch this space!

**Comment by dshoreman** [comment]
@e-alfred I've been able to replicate this in a VM and add a fix which should solve the issue without requiring the `en_US` locale to be enabled. I'll release a new version with the fix shortly, thanks again for reporting the issue!

**Comment by dshoreman** [comment]
Fix has been pushed to master, and should show up in AUR as v1.3.2 shortly if you're on Arch. If you still have the problem with the update, feel free to reopen
